# Run Chromatic on the main branch after a PR has been merged (currently required to update the baseline when doing "squash" merge for PRs).
trigger:
  branches:
    include:
      - main

# Run Chromatic on every Pull Request targeting the "main" branch as destination.
pr:
  branches:
    include:
      - main

variables:
  - group: Azure DevOps

steps:
  - task: UseNode@1
    displayName: Use Node.js >=20.0.0
    inputs:
      version: ">=20.0.0"
      checkLatest: true

  # Chromatic needs the full Git history to compare the baselines.
  # Checkout must happen before the setup template.
  - checkout: self
    displayName: Get full Git history
    fetchDepth: 0

  - task: Cache@2
    displayName: Cache pnpm
    inputs:
      key: '"pnpm" | "$(Agent.OS)" | pnpm-lock.yaml'
      restoreKeys: |
        "pnpm" | "$(Agent.OS)"
        "pnpm"
      path: $(Pipeline.Workspace)/.pnpm-store

  - script: |
      corepack enable
      corepack prepare pnpm@latest-8 --activate
      pnpm config set store-dir $(Pipeline.Workspace)/.pnpm-store
    displayName: Setup pnpm

  - task: npmAuthenticate@0
    displayName: Authenticate to private npm feed
    inputs:
      workingFile: .npmrc

  - script: pnpm install --frozen-lockfile
    displayName: pnpm install

  # Accepting the baseline automatically when Chromatic is executed on the "main" branch.
  # Running Chromatic on the "main" branch allow us to use "squash" merge for PRs, see: https://www.chromatic.com/docs/custom-ci-provider/#squashrebase-merge-and-the-main-branch.
  # Furthermore, changes from PR doesn't seem to be updating the baseline at all but I don't know why, it seems like a bug with ADO.
  - task: CmdLine@2
    displayName: Chromatic (main branch)
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    inputs:
      - script: pnpm dlx chromatic --only-changed --skip renovate/** --auto-accept-changes main
    env:
      CHROMATIC_PROJECT_TOKEN: $(CHROMATIC_PROJECT_TOKEN)

  - task: CmdLine@2
    displayName: Chromatic (PR)
    condition: eq(variables['Build.Reason'], 'PullRequest')
    inputs:
      - script: pnpm dlx @workleap/chromatic-ado --only-changed --skip renovate/**
    env:
      CHROMATIC_PROJECT_TOKEN: $(CHROMATIC_PROJECT_TOKEN)
      PULL_REQUEST_COMMENT_ACCESS_TOKEN: $(PULL_REQUEST_COMMENT_ACCESS_TOKEN)
